export const BASKET_ADD_ITEM = 'BASKET_ADD_ITEM';
export const BASKET_REMOVE_ITEM = 'BASKET_REMOVE_ITEM';
export const BASKET_SAVE_SHIPPING_ADDRESS = 'BASKET_SAVE_SHIPPING_ADDRESS';
export const BASKET_SAVE_PAYMENT_METHOD = 'BASKET_SAVE_PAYMENT_METHOD';
export const BASKET_RESET = 'BASKET_RESET';
